### ISSUE TITLE
[docker] upgrading image results in failed hive-server2 connection with error: string argument expected, got 'bytes'

### ISSUE THREAD

**Issue by dncnbuck** [cloudera/hue#1698]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
Upgrading the docker image from `gethue/hue:20201227-041245` -> `gethue/hue:20201228-085408` results in failed hive-server2 connection with error,
```
[27/Jan/2021 02:46:36 -0800] conf         ERROR    The application won't work without a running HiveServer2.
Traceback (most recent call last):
  File "/usr/share/hue/apps/hive/src/hive/conf.py", line 56, in config_validator
    handle = server.execute_and_wait(query, timeout_sec=10.0)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/dbms.py", line 973, in execute_and_wait
    handle = self.client.query(query)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1420, in query
    return self._client.execute_async_query(query, statement, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 988, in execute_async_query
    return self.execute_async_statement(statement=query_statement, conf_overlay=configuration, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1021, in execute_async_statement
    (res, session) = self.call_return_result_and_session(thrift_function, thrift_request, session=session)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 765, in call_return_result_and_session
    session = self.open_session(self.user)
  File "/usr/share/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 686, in open_session
    res = self._client.OpenSession(req)
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_util.py", line 428, in wrapper
    return attr(*args, **kwargs)
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_util.py", line 497, in wrapper
    ret = res(*args, **kwargs)
  File "/usr/share/hue/apps/beeswax/gen-py/TCLIService/TCLIService.py", line 228, in OpenSession
    self.send_OpenSession(req)
  File "/usr/share/hue/apps/beeswax/gen-py/TCLIService/TCLIService.py", line 237, in send_OpenSession
    self._oprot.trans.flush()
  File "/usr/share/hue/build/env/lib/python3.6/site-packages/thrift/transport/TTransport.py", line 179, in flush
    self.__trans.write(out)
  File "/usr/share/hue/desktop/core/src/desktop/lib/thrift_/http_client.py", line 86, in write
    self._wbuf.write(buf)
TypeError: string argument expected, got 'bytes'
```
Hive transport mode is http and no configuration has been changed between deployments.

It should be noted the issue is also visible in the following two images

* Fully operational, TAG: [gethue/hue:latest-py2](https://hub.docker.com/layers/gethue/hue/latest-py2/images/sha256-5d0457d1a4f5085298037333fd701365d5cb2b36f4846c5da673ee48ae39de40?context=explore), DIGEST:sha256:5d0457d1a4f5085298037333fd701365d5cb2b36f4846c5da673ee48ae39de40
* Results in Hive-server2 connection issue: TAG: [gethue/hue:latest](https://hub.docker.com/layers/gethue/hue/latest/images/sha256-50c820cdd720eff3f308232d47dcca508410b2f7dac1fea593da86a55b425e2f?context=explore), DIGEST:sha256:50c820cdd720eff3f308232d47dcca508410b2f7dac1fea593da86a55b425e2f

There are not many changes on the 28th,December 2020 but might it be related to the underlying changes introduced in the dockerfile made here? https://github.com/cloudera/hue/commit/b4160a2defeb27f7af02b27017fdf9e0922ab87b#diff-917e6a8042dd61a735b904996cf9d6446e41922c6034141d22196d142018664e

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
4.8

**Comment by romainr** [comment]
It could be a special case where you upgraded from a Python 2 Hue to a Python 3 one.

Deleting the older sessions in the beeswax_session should fix it.

**Comment by dncnbuck** [comment]
sadly deleting the beeswax_sessions did not resolve the issue.

**Comment by romainr** [comment]
I see you are using HTTP thrift and not the binary one. https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/lib/thrift_/http_client.py might not be ported yet to Python 3

**Comment by dncnbuck** [comment]
Ok thanks for the help. I'll use the "latest-py2"  image for the time being and if time allows could help support with the change.

Thanks

**Comment by romainr** [comment]
@agl29
