### ISSUE TITLE
Error when looking for details of a Hive task 

### ISSUE THREAD

**Issue by divincode** [cloudera/hue#2842]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
Traceback (most recent call last):
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 43, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 86, in job
    app_id = json.loads(request.body)['queryId']
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Steps to reproduce it?
Create a Hadoop Cluster, with hive and hue on it.Run a hive query and click the hive task id to look into the details you will encounter the bug. 
<img width="1440" alt="Screenshot 2022-05-12 at 2 27 09 PM" src="https://user-images.githubusercontent.com/35135348/168033109-a1fc9a2f-5a93-4366-8188-a7496d6f40e8.png">

The hue.ini file must have the following parameters .
hue-ini.jobbrowser | enable_hive_query_browser | true 
hue-ini.jobbrowser | enable_query_browser | false
hue-ini.jobbrowser | enable_queries_list | true 
hue-ini.jobbrowser | disable_killing_jobs | false 
hue-ini.jobbrowser | share_jobs | true 

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
4.10.0

RCA:
The click for looking details of Hive task in generating  a call /api/job/<interface>(query-hive) - app_id = json.loads(request.body)['queryId'] this line is breaking . The template makes a call which does not send queryid in the post body in the mocko file in the job browser application.

**Comment by Harshg999** [comment]
IIRC, this has been fixed recently @divincode.
Can you try with the latest master?

**Comment by divincode** [comment]
Btw Harshg999 when will the release 4.11.0 be released?

**Comment by divincode** [comment]
Hi @Harshg999 the issue still seems to persist .I have tried it with the master but still does not work. I instrospected the code in the master but the code has not be altered ,
        return $.post("/jobbrowser/api/job/" + vm.interface(), {
          cluster: ko.mapping.toJSON(vm.compute),
          app_id: ko.mapping.toJSON(self.id),
          interface: ko.mapping.toJSON(vm.interface),
          pagination: ko.mapping.toJSON(self.pagination)
        }, function (data) {
          if (data.status == 0) {
            if (data.app) {
              huePubSub.publish('jobbrowser.data', [data.app]);
            }
            if (callback) {
              callback(data);
            }
          } else {
            $(document).trigger("error", data.message);
          }
        });
      };
<img width="1440" alt="Screenshot 2022-05-18 at 8 25 40 AM" src="https://user-images.githubusercontent.com/35135348/168947893-9cda05a0-05ee-447e-9bd5-031b7b81fdff.png">

**Comment by Harshg999** [comment]
> Btw Harshg999 when will the release 4.11.0 be released?

Its in the pipeline, most probably next month I think.

**Comment by Harshg999** [comment]
> Hi @Harshg999 the issue still seems to persist .I have tried it with the master but still does not work. I instrospected the code in the master but the code has not be altered , return $.post("/jobbrowser/api/job/" + vm.interface(), { cluster: ko.mapping.toJSON(vm.compute), app_id: ko.mapping.toJSON(self.id), interface: ko.mapping.toJSON(vm.interface), pagination: ko.mapping.toJSON(self.pagination) }, function (data) { if (data.status == 0) { if (data.app) { huePubSub.publish('jobbrowser.data', [data.app]); } if (callback) { callback(data); } } else { $(document).trigger("error", data.message); } }); }; <img alt="Screenshot 2022-05-18 at 8 25 40 AM" width="1440" src="https://user-images.githubusercontent.com/35135348/168947893-9cda05a0-05ee-447e-9bd5-031b7b81fdff.png">

Hi @divincode, this was an incomplete feature implementation and is not supported upstream. I remember I removed some stale code but left the UI stuff and some config stuff.

Any chance you have `enable_hive_query_browser=true` under `[jobbrowser]`? If yes, can you try setting it as false (by default its false) and we should not see this link popping up in the log div.

**Comment by divincode** [comment]
Ya ok Thank u
